### ISSUE TITLE
Support refreshing the view

### ISSUE THREAD

**Issue by mathstuf** [nbedos/cistern#10]
It'd be nice to have an `r` (or similar) binding to refresh the call. It seems that once a pipeline is complete, no more requests are sent to update it. This is reasonable, however, if I retry a failed job, `citop` doesn't show it until I restart it.

**Comment by mathstuf** [comment]
If told that I want to watch `HEAD` or `master`, refreshing what commit this means should also be supported in some way.

**Comment by nbedos** [comment]
Yes, that's planned.

**Comment by simplelife2010** [comment]
It would also be nice if refreshing would also display new pipelines. Currently, if after running cistern a new pipeline starts, it is never displayed.

**Comment by mathstuf** [comment]
I've seen them show up if I leave it open overnight, but I sometimes have to refresh manually over the course of the day.

**Comment by simplelife2010** [comment]
I have a lot of pipelines starting over the day, they will not appear in the list. How do you refresh manually? I have not seen any key binding to do that.

I have to quit and restart.

**Comment by mathstuf** [comment]
You can press `r` to choose a ref. If it isn't different than before, it will "ignore" you, but you can swap between `master` and `HEAD` which should refresh things.

**Comment by simplelife2010** [comment]
Which version do you use? I don't seem to have this feature in my version cistern 0.2.0-5-ga124d04-darwin-amd64.

**Comment by mathstuf** [comment]
Ah, right. I was testing some pre-releases for fixes to other issues I opened. 0.2.0dev6-linux-amd64

**Comment by nbedos** [comment]
I made changes related to this issue on the following branch: https://github.com/nbedos/cistern/tree/feature/ref_navigation

You can now use the following keys:

* **r** or **F5** to refresh the view in order to list new pipelines or get updates about jobs that have been restarted
* **f** to follow the current git reference in case it changed (e.g. if you ran `cistern master` in a terminal and then added a commit to `master` from another terminal you can now press **f** to have `cistern` monitor the last commit instead of the second to last). 
* **g** to open a prompt to input the name of a git reference to monitor. For local repositories this comes with autocomplete to make our lives easier.

What do you think?

**Comment by simplelife2010** [comment]
I like.
Would it be possible to do the refresh automatically? Right now, status of already shown pipeline jobs including duration is automatically updated. For new pipelines I have to refresh manually, which works fine. But intuitively I would expect this the be done automatically.

The f key works fine.

The g key shows up a table with all the refs, but choosing one does not have an effect.

**Comment by nbedos** [comment]
Thanks for the feedback!

I pushed changes on the same branch that add the polling strategy used by `cistern` to the configuration file:

```toml
[providers.polling]
# cistern gets information from providers by sending requests to their API at increasing intervals.
# The duration between two consecutive requests for a given API resource starts at
# the value defined by the key "initial-interval" and exponentially increases until it reaches
# the duration "max-interval". Each time a requests returns new data (e.g. a new pipeline, or a
# pipeline that changed since the last request), the duration between requests is reset to the value
# of "initial-interval" and starts increasing again.

# Duration of the initial interval in seconds (integer, default: 10)
initial-interval = 10

# Duration of the maximal interval in seconds (integer, default: 120)
max-interval = 120

# Continue polling once the duration "max-interval" is reached. The duration between two requests
# is capped at "max-interval". (boolean, default: false)
forever = false
```
Long story short, setting `forever = true` and maybe reducing the value of `max-interval` will give you almost live updates even long after the first pipelines have finished. Just be aware that it causes `cistern` to endlessly send requests to your source and CI providers.

For the *g* key you need to either type the name of the reference (or use autocomplete (*TAB* key) to fill the prompt with a reference from the list) and then press *Enter*. *Enter* won't select  a reference from the list, it's just used for finishing the entry. I was afraid this would be confusing but I can't use *Enter* for both autocomplete (like *TAB*) and finishing the entry. Maybe disabling the up/down arrows would encourage typing a reference instead of navigating the list?
