### ISSUE TITLE
Allow setting tokens via env variables

### ISSUE THREAD

**Issue by SuperSandro2000** [nbedos/cistern#13]
I already have a lot of tokens in my ENV variables and would like to re-use them.

**Comment by mathstuf** [comment]
Some way to say "look at this envvar" from the config file would be a good way to do this. I guess making the password be something like:

```
token = "string" # current status
token = { value = "string" } # what it is interpreted as
token = { environment = "variable" }
```

This would also be possible:

```
token = { process = [ ... ] }
```

Guidance from https://github.com/rust-lang/rfcs/pull/2730 would be useful to know how to interpret the `process` case on different platforms.

**Comment by nbedos** [comment]
I'm not fond of changing the configuration file just to get tokens from environment variables because it seems like a very narrow use case. It also encourages sharing the same token with multiple applications which is not ideal.

However the `token-from-process` used by `cargo` seems like a good idea since it should cover most use cases of people storing their secrets outside of the configuration file. I'm not too worried about cross platform compatibility since Golang provides [`exec.Command`](https://golang.org/pkg/os/exec/#Command) to run arbitrary commands and the signature of this function matches the value expected for `token-from-process`.

So setting a token could be done in a couple of ways:
```toml
# Token stored in the configuration file
token = "mytoken"
# Token stored in an environment variable
token-from-process = ["bash", "-c", "echo $MY_API_TOKEN"]
# Generic case: token returned by calling `executable arg1 arg2 ...`
token-from-process = ["executable", "arg1", "arg2"]
```
As mentioned in the RFC the process inherits `stdin` and `stderr` so people could store their tokens in their password manager and be prompted for a password when running `cistern`. It seems like a good solution. Thanks @mathstuf for pointing out the RFC.
